git clone https://github.com/opscode-cookbooks/rabbitmq.git
git clone https://github.com/opscode-cookbooks/php.git
git clone https://github.com/opscode-cookbooks/lvm.git
git clone https://github.com/opscode-cookbooks/emacs.git
git clone https://github.com/opscode-cookbooks/thrift.git
git clone https://github.com/opscode-cookbooks/trac.git
git clone https://github.com/opscode-cookbooks/mysql.git
git clone https://github.com/opscode-cookbooks/build-essential.git
git clone https://github.com/opscode-cookbooks/python.git
git clone https://github.com/opscode-cookbooks/postgresql.git
git clone https://github.com/opscode-cookbooks/ark.git
git clone https://github.com/opscode-cookbooks/nginx.git
git clone https://github.com/opscode-cookbooks/jenkins.git
git clone https://github.com/opscode-cookbooks/openssl.git
git clone https://github.com/opscode-cookbooks/yum.git
git clone https://github.com/opscode-cookbooks/haproxy.git
git clone https://github.com/opscode-cookbooks/nagios.git
git clone https://github.com/opscode-cookbooks/powershell.git
git clone https://github.com/opscode-cookbooks/firewall.git
git clone https://github.com/opscode-cookbooks/apt.git
git clone https://github.com/opscode-cookbooks/logrotate.git
git clone https://github.com/opscode-cookbooks/mercurial.git
git clone https://github.com/opscode-cookbooks/openssh.git
git clone https://github.com/opscode-cookbooks/git.git
git clone https://github.com/opscode-cookbooks/cron.git
git clone https://github.com/opscode-cookbooks/database.git
git clone https://github.com/opscode-cookbooks/pdns.git
git clone https://github.com/opscode-cookbooks/zenoss.git
git clone https://github.com/opscode-cookbooks/transmission.git
git clone https://github.com/opscode-cookbooks/resolver.git
git clone https://github.com/opscode-cookbooks/samba.git
git clone https://github.com/opscode-cookbooks/radiant.git
git clone https://github.com/opscode-cookbooks/perl.git
git clone https://github.com/opscode-cookbooks/pacman.git
git clone https://github.com/opscode-cookbooks/munin.git
git clone https://github.com/opscode-cookbooks/jetty.git
git clone https://github.com/opscode-cookbooks/gecode.git
git clone https://github.com/opscode-cookbooks/dynect.git
git clone https://github.com/opscode-cookbooks/drbd.git
git clone https://github.com/opscode-cookbooks/ant.git
git clone https://github.com/opscode-cookbooks/reprepro.git
git clone https://github.com/opscode-cookbooks/varnish.git
git clone https://github.com/opscode-cookbooks/ohai.git
git clone https://github.com/opscode-cookbooks/ucspi-tcp.git
git clone https://github.com/opscode-cookbooks/ntp.git
git clone https://github.com/opscode-cookbooks/aws.git
git clone https://github.com/opscode-cookbooks/apache2.git
git clone https://github.com/opscode-cookbooks/openldap.git
git clone https://github.com/opscode-cookbooks/squid.git
git clone https://github.com/opscode-cookbooks/windows.git
git clone https://github.com/opscode-cookbooks/application.git
git clone https://github.com/opscode-cookbooks/application_python.git
git clone https://github.com/opscode-cookbooks/application_ruby.git
git clone https://github.com/opscode-cookbooks/application_php.git
git clone https://github.com/opscode-cookbooks/supervisor.git
git clone https://github.com/opscode-cookbooks/wix.git
git clone https://github.com/opscode-cookbooks/memcached.git
git clone https://github.com/opscode-cookbooks/passenger_apache2.git
git clone https://github.com/opscode-cookbooks/tomcat.git
git clone https://github.com/opscode-cookbooks/chef-client.git
git clone https://github.com/opscode-cookbooks/nova.git
git clone https://github.com/opscode-cookbooks/ufw.git
git clone https://github.com/opscode-cookbooks/wordpress.git
git clone https://github.com/opscode-cookbooks/iis.git
git clone https://github.com/opscode-cookbooks/rsyslog.git
git clone https://github.com/opscode-cookbooks/chef-server.git
git clone https://github.com/opscode-cookbooks/postfix.git
git clone https://github.com/opscode-cookbooks/java.git
git clone https://github.com/opscode-cookbooks/cloudkick.git
git clone https://github.com/opscode-cookbooks/motd-tail.git
git clone https://github.com/opscode-cookbooks/logwatch.git
git clone https://github.com/opscode-cookbooks/sudo.git
git clone https://github.com/opscode-cookbooks/pxe_dust.git
git clone https://github.com/opscode-cookbooks/ossec.git
git clone https://github.com/opscode-cookbooks/subversion.git
git clone https://github.com/opscode-cookbooks/maradns.git
git clone https://github.com/opscode-cookbooks/jpackage.git
git clone https://github.com/opscode-cookbooks/gems.git
git clone https://github.com/opscode-cookbooks/apparmor.git
git clone https://github.com/opscode-cookbooks/maven.git
git clone https://github.com/opscode-cookbooks/fail2ban.git
git clone https://github.com/opscode-cookbooks/zsh.git
git clone https://github.com/opscode-cookbooks/erlang.git
git clone https://github.com/opscode-cookbooks/runit.git
git clone https://github.com/opscode-cookbooks/openvpn.git
git clone https://github.com/opscode-cookbooks/activemq.git
git clone https://github.com/opscode-cookbooks/xfs.git
git clone https://github.com/opscode-cookbooks/sqlite.git
git clone https://github.com/opscode-cookbooks/couchdb.git
git clone https://github.com/opscode-cookbooks/bluepill.git
git clone https://github.com/opscode-cookbooks/omnibus.git
git clone https://github.com/opscode-cookbooks/ssh_known_hosts.git
git clone https://github.com/opscode-cookbooks/application_nginx.git
git clone https://github.com/opscode-cookbooks/application_java.git
git clone https://github.com/opscode-cookbooks/users.git
git clone https://github.com/opscode-cookbooks/tmux.git
git clone https://github.com/opscode-cookbooks/webpi.git
git clone https://github.com/opscode-cookbooks/freebsd.git
git clone https://github.com/opscode-cookbooks/daemontools.git
git clone https://github.com/opscode-cookbooks/selinux.git
git clone https://github.com/opscode-cookbooks/unicorn.git
git clone https://github.com/opscode-cookbooks/rsync.git
git clone https://github.com/opscode-cookbooks/keepalived.git
git clone https://github.com/opscode-cookbooks/djbdns.git
git clone https://github.com/opscode-cookbooks/ubuntu.git
git clone https://github.com/opscode-cookbooks/iptables.git
git clone https://github.com/opscode-cookbooks/god.git
git clone https://github.com/opscode-cookbooks/jira.git
git clone https://github.com/opscode-cookbooks/horizon.git
git clone https://github.com/opscode-cookbooks/glance.git
git clone https://github.com/opscode-cookbooks/keystone.git
git clone https://github.com/opscode-cookbooks/whitelist-node-attrs.git
git clone https://github.com/opscode-cookbooks/chef_handler.git
git clone https://github.com/opscode-cookbooks/xml.git
git clone https://github.com/opscode-cookbooks/nscd.git
git clone https://github.com/opscode-cookbooks/heartbeat.git
git clone https://github.com/opscode-cookbooks/boost.git
git clone https://github.com/opscode-cookbooks/screen.git
git clone https://github.com/opscode-cookbooks/tftp.git
git clone https://github.com/opscode-cookbooks/zlib.git
git clone https://github.com/opscode-cookbooks/dmg.git
git clone https://github.com/opscode-cookbooks/snort.git
git clone https://github.com/opscode-cookbooks/homebrew.git
git clone https://github.com/opscode-cookbooks/vim.git
git clone https://github.com/opscode-cookbooks/swift.git
git clone https://github.com/opscode-cookbooks/stompserver.git
git clone https://github.com/opscode-cookbooks/sql_server.git
git clone https://github.com/opscode-cookbooks/sbuild.git
git clone https://github.com/opscode-cookbooks/partial_search.git
git clone https://github.com/opscode-cookbooks/man.git
git clone https://github.com/opscode-cookbooks/kickstart.git
git clone https://github.com/opscode-cookbooks/imagemagick.git
git clone https://github.com/opscode-cookbooks/hadoop.git
git clone https://github.com/opscode-cookbooks/gunicorn.git
git clone https://github.com/opscode-cookbooks/gnu_parallel.git
git clone https://github.com/opscode-cookbooks/getting-started.git
git clone https://github.com/opscode-cookbooks/chef.git
git clone https://github.com/opscode-cookbooks/7-zip.git
